#!/usr/bin/env python3
"""
Created on Wed Feb 26 21:22:05 2025

@author: ghiggi
"""

GMI_RECEIPTS = {
    "10 + 18 GHz": {
        "R": {
            "name": "19V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "19H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "10H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "19 + 23 GHz": {
        "R": {
            "name": "23V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "19V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "19H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "36 + 89 GHz": {
        "R": {
            "name": "89V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "37H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "165 + 183 GHz": {
        "R": {
            "name": "165V",
            "vmin": 50,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183V7",
            "vmin": 50,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183V3",
            "vmin": 50,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
    "36 + 88 + 165 GHz": {
        "R": {
            "name": "165V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "37H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "NRL_37": {
        "R": {
            "name": "PCT_37",
            "vmin": 260,
            "vmax": 280,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "37V",
            "vmin": 160,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "37H",
            "vmin": 180,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
    "NRL_89": {
        "R": {
            "name": "PCT_89",
            "vmin": 230,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 255,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "89V",
            "vmin": 275,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
}

TMI_RECEIPTS = {
    "10 + 18 GHz": {
        "R": {
            "name": "19V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "19H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "10H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "19 + 21 GHz": {
        "R": {
            "name": "21V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "19V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "19H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "36 + 89 GHz": {
        "R": {
            "name": "89V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "37H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "NRL_36": {
        "R": {
            "name": "PCT_36",
            "vmin": 260,
            "vmax": 280,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "36H",
            "vmin": 160,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "36V",
            "vmin": 180,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
    "NRL_89": {
        "R": {
            "name": "PCT_89",
            "vmin": 230,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 255,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "89V",
            "vmin": 275,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
}

SSMIS_RECEIPTS = {
    "19 + 22 GHz": {
        "R": {
            "name": "22V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "19V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "19H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "37 + 91 GHz": {
        "R": {
            "name": "91V",
            "vmin": 65,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "91H",
            "vmin": 65,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "37H",
            "vmin": 65,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "183 GHz": {
        "R": {
            "name": "183H7",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183H3",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183H1",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
    "NRL_37": {
        "R": {
            "name": "PCT_37",
            "vmin": 260,
            "vmax": 280,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "37V",
            "vmin": 160,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "37H",
            "vmin": 180,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
    "NRL_91": {
        "R": {
            "name": "PCT_91",
            "vmin": 230,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "91H",
            "vmin": 255,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "91V",
            "vmin": 275,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
}

SSMI_RECEIPTS = {
    "19 + 22 GHz": {
        "R": {
            "name": "22V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "19V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "19H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "37 + 85 GHz": {
        "R": {
            "name": "85V",
            "vmin": 65,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "85H",
            "vmin": 65,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "37H",
            "vmin": 65,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "NRL_37": {
        "R": {
            "name": "PCT_37",
            "vmin": 260,
            "vmax": 280,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "37V",
            "vmin": 160,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "37H",
            "vmin": 180,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
    "NRL_85": {
        "R": {
            "name": "PCT_85",
            "vmin": 230,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "85H",
            "vmin": 255,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "85V",
            "vmin": 275,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
}

AMSRE_RECEIPTS = {
    "10 + 18 GHz": {
        "R": {
            "name": "18.7V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "18.7H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "10.65H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "19 + 23 GHz": {
        "R": {
            "name": "23.8V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "18.7V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "18.7H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "37 + 89 GHz": {
        "R": {
            "name": "89V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "36.5H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "NRL_36.5": {
        "R": {
            "name": "PCT_36.5",
            "vmin": 260,
            "vmax": 280,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "36.5V",
            "vmin": 160,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "36.5H",
            "vmin": 180,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
    "NRL_89": {
        "R": {
            "name": "PCT_89",
            "vmin": 230,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 255,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "89V",
            "vmin": 275,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
}
AMSR2_RECEIPTS = {
    "10 + 18 GHz": {
        "R": {
            "name": "18.7V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "18.7H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "10.65H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "18 + 23 GHz": {
        "R": {
            "name": "23.8V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "18.7V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "18.7H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "37 + 89 GHz": {
        "R": {
            "name": "89V",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "36.5H",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "NRL_36.5": {
        "R": {
            "name": "PCT_36.5",
            "vmin": 260,
            "vmax": 280,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "36.5V",
            "vmin": 160,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "36.5H",
            "vmin": 180,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
    "NRL_89": {
        "R": {
            "name": "PCT_89",
            "vmin": 230,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "89H",
            "vmin": 255,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "B": {
            "name": "89V",
            "vmin": 275,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": False,
        },
        "global_normalization": False,
    },
}
ATMS_RECEIPTS = {
    "31 + 88 + 165 GHz": {
        "R": {
            "name": "165.5QH",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "88.2QV",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "31.4QV",
            "vmin": 65,
            "vmax": 320,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": False,
    },
    "165 + 183 GHz": {
        "R": {
            "name": "165.5QH",
            "vmin": 50,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183.31QH7",
            "vmin": 50,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183.31QH3",
            "vmin": 50,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
    "183 GHz": {
        "R": {
            "name": "183.31QH7",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183.31QH3",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183.31QH1",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
}

AMSUB_RECEIPTS = {
    "150 + 183 GHz": {
        "R": {
            "name": "150V0.9",
            "vmin": 100,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183.31V7",
            "vmin": 100,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183.31V1",
            "vmin": 100,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
    "183 GHz": {
        "R": {
            "name": "183.31V7",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183.31V3",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183.31V1",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
}
MHS_RECEIPTS = {
    "157 + 183 GHz": {
        "R": {
            "name": "157V",
            "vmin": 100,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "190.31V",
            "vmin": 100,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183.31H1",
            "vmin": 100,
            "vmax": 290,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
    "183 GHz": {
        "R": {
            "name": "190.31V",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183.31H3",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183.31H1",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
}
SAPHIR_RECEIPTS = {
    "183 GHz": {
        "R": {
            "name": "183.31H6.8",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "G": {
            "name": "183.31H2.8",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "B": {
            "name": "183.31H1.1",
            "vmin": 100,
            "vmax": 300,
            "vmin_dynamic": False,
            "vmax_dynamic": False,
            "invert": True,
        },
        "global_normalization": True,
    },
}

# ----------------------------------------
# NRL composites: https://science.nrlmry.navy.mil/geoips/tcweb/active/?stormId=SH202025&sensor=amsr2&product=37pct

# TROPICS Water vapour composite
# - 10, 9, 8 (vmax=290, vmin=140)
# - 186.51 184.41 118.58 GHz

# TROPICS Window channel composite
# - 0, 1, 11 (vmax=300, vmin=150 for 0-1, (min=125,vmax=300 for 11)
# - 91.655 114.50 190.31 GHz


PMW_RECEIPTS = {
    "GMI": GMI_RECEIPTS,
    "TMI": TMI_RECEIPTS,
    "SSMIS": SSMIS_RECEIPTS,
    "SSMI": SSMI_RECEIPTS,
    "AMSRE": AMSRE_RECEIPTS,
    "AMSR2": AMSR2_RECEIPTS,
    "ATMS": ATMS_RECEIPTS,
    "AMSUB": AMSUB_RECEIPTS,
    "MHS": MHS_RECEIPTS,
    "SAPHIR": SAPHIR_RECEIPTS,
}
