PIA:
  _FillValue: -9999.9
  description: The effective 2-way path integrated attenuation.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SRT/pathAtten
  standard_name: pathAtten
  units: dB
PIA_Final:
  _FillValue: -9999.9
  description: The final estimates of path integrated attenuation caused by precipitation particles.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/piaFinal
  standard_name: piaFinal
  units: dB
PIA_HB:
  _FillValue: -9999.9
  description: The 2-way path integrated attenuation of HB.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SRT/PIAhb
  standard_name: PIAhb
  units: dB
PIA_Hybrid:
  _FillValue: -9999.9
  description: The 2-way PIA from a weighted combination of HB and SRT.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SRT/PIAhybrid
  standard_name: PIAhybrid
  units: dB
attenuationNP:
  _FillValue: -9999.9
  description: " Vertical profile of attenuation by non-precipitation particles.\n\
    \                                    (cloud liquid water, cloud ice water, water\
    \ vapor, and oxygen molecules)\n                                "
  dims:
  - along_track
  - cross_track
  - range
  ndims: 3
  offset_scale: []
  path: VER/attenuationNP
  standard_name: attenuationNP
  units: dB/km
binBBBottom:
  _FillValue:
  - -1111
  - -9999
  description: Range bin number for the bottom of the bright band.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/binBBBottom
  standard_name: binBBBottom
  units: ''
binBBPeak:
  _FillValue:
  - -1111
  - -9999
  description: Range bin number for the peak of the bright band.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/binBBPeak
  standard_name: binBBPeak
  units: ''
binBBTop:
  _FillValue:
  - -1111
  - -9999
  description: Range bin number for the top of the bright band.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/binBBTop
  standard_name: binBBTop
  units: ''
binClutterFreeBottom:
  _FillValue: -9999
  description: Range bin number for clutter free bottom.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/binClutterFreeBottom
  standard_name: binClutterFreeBottom
  units: ''
binDFRmMLBottom:
  _FillValue:
  - 0
  - -1111
  - -9999
  description: Range bin number for the for melting layer bottom.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/binDFRmMLBottom
  standard_name: binDFRmMLBottom
  units: ''
binDFRmMLTop:
  _FillValue:
  - 0
  - -1111
  - -9999
  description: Range bin number for the for melting layer top.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/binDFRmMLTop
  standard_name: binDFRmMLTop
  units: ''
binEchoBottom:
  _FillValue: -9999
  description: Range bin number for ... (TODO)
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/binEchoBottom
  standard_name: binEchoBottom
  units: ''
binRealSurface:
  _FillValue: -9999
  description: Range bin number for real surface.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/binRealSurface
  standard_name: binRealSurface
  units: ''
binStormTop:
  _FillValue: -9999
  description: Range bin number for the storm top.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/binStormTop
  standard_name: binStormTop
  units: ''
binZeroDeg:
  _FillValue: []
  description: " Range bin number with 0 \xB0C.\n                          For NS\
    \ and MS: 177 --> 0 \xB0C at the surface.\n                          For HS: 89\
    \ --> 0 \xB0C at the surface.\n                      "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: VER/binZeroDeg
  standard_name: binZeroDeg
  units: ''
elevation:
  _FillValue: -9999.9
  description: Elevation of the measurement point. It is a copy of DEMHmean of level 1B product.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/elevation
  standard_name: elevation
  units: m
flagBB:
  _FillValue:
  - -1111
  - -9999
  description: " Flag for Bright Band. \n                          0 : BB not detected\n\
    \                          1 : BB detected\n                          "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/flagBB
  standard_name: flagBB
  units: ''
flagHeavyIcePrecip:
  _FillValue: -99
  description: " Flag for heavy precip based on reflectivity thresholds.\n       \
    \                      See GPM ATBD for more information.\n                  \
    \       "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/flagHeavyIcePrecip
  standard_name: flagHeavyIcePrecip
  units: ''
flagPrecip:
  _FillValue: -9999
  description: " Flag for precipitation. \n                          0 : No precipitation\n\
    \                          1 : Precipitation\n                          "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/flagPrecip
  standard_name: flagPrecip
  units: ''
flagShallowRain:
  _FillValue:
  - -1111
  - -9999
  description: " Flag for shallow precipitation: \n                             0\
    \ : No shallow rain\n                             10: Shallow isolated (maybe)\n\
    \                             11: Shallow isolated (certain)\n               \
    \              20: Shallow non-isolated (maybe)\n                            \
    \ 21: Shallow non-isolated (certain)\n                         "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/flagShallowRain
  standard_name: flagShallowRain
  units: ''
flagSigmaZeroSaturation:
  _FillValue: 99
  description: " Flag to show whether echoPower is under a saturated level.\n    \
    \                      0 : Under saturated lvel\n                          1 :\
    \ Possible saturated level at real surface\n                          2 : Saturated\
    \ level at real surface\n                          "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/flagSigmaZeroSaturation
  standard_name: flagSigmaZeroSaturation
  units: ''
heightBB:
  _FillValue:
  - -1111.1
  - -9999.9
  description: Height of the bright band.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/heightBB
  standard_name: heightBB
  units: m
heightStormTop:
  _FillValue: -9999.9
  description: Height of storm top.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/heightStormTop
  standard_name: heightStormTop
  units: m
heightZeroDeg:
  _FillValue: -9999.9
  description: Height of freezing level (0 degrees C level).
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: VER/heightZeroDeg
  standard_name: heightZeroDeg
  units: m
localZenithAngle:
  _FillValue: -9999.9
  description: Local zenith angle of each ray (scLocalZenith).
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/localZenithAngle
  standard_name: localZenithAngle
  units: degree
paramDSD:
  _FillValue: -9999.9
  description: Parameters of the drop size distribution.
  dims:
  - along_track
  - cross_track
  - range
  - nDSD
  ndims: 4
  offset_scale: []
  path: SLV/paramDSD
  standard_name: paramDSD
  units: ''
phase:
  _FillValue: 255
  description: Phase state of the precipitation. To be decoded following GPM ATBD.                     "
  dims:
  - along_track
  - cross_track
  - range
  ndims: 3
  offset_scale: []
  path: DSD/phase
  standard_name: phase
  units: ''
precipRate:
  _FillValue: -9999.9
  description: Precipitation rate.
  dims:
  - along_track
  - cross_track
  - range
  ndims: 3
  offset_scale: []
  path: SLV/precipRate
  standard_name: precipRate
  units: mm/hr
precipRateAve24:
  _FillValue: -9999.9
  description: Average of precipitation rate between 2 and 4km height.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/precipRateAve24
  standard_name: precipRateAve24
  units: mm/hr
precipRateESurface:
  _FillValue: -9999.9
  description: Precipitation rate at the estimated surface.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/precipRateESurface
  standard_name: precipRateESurface
  units: mm/hr
precipRateESurface2:
  _FillValue: -9999.9
  description: Estimates Surface Precipitation using alternate method.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: Experimental/precipRateESurface2
  standard_name: precipRateESurface2
  units: mm/hr
precipRateNearSurface:
  _FillValue: -9999.9
  description: Precipitation rate at the near surface.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/precipRateNearSurface
  standard_name: precipRateNearSurface
  units: mm/hr
precipWaterIntegrated:
  _FillValue: -9999.9
  description: Precipitation water vertically integrated.
  dims:
  - along_track
  - cross_track
  - LS
  ndims: 3
  offset_scale: []
  path: SLV/precipWaterIntegrated
  standard_name: precipWaterIntegrated
  units: mm/hr
qualityBB:
  _FillValue:
  - -1111
  - -9999
  description: " Quality of the bright band detection: \n                        \
    \          0 : BB not detected in the case of rain\n                         \
    \         1 : Clear bright band\n                                  2 : Not so\
    \ clear bright band\n                                  3 : Smeared bright band\n\
    \                              "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/qualityBB
  standard_name: qualityBB
  units: m
qualityFlag:
  _FillValue:
  - -1111
  - -9999
  description: " Quality flag: \n                                  0 : High quality.\
    \ No issues\n                                  1 : Low quality (DPR modules had\
    \ warnings but still made a retrieval)\n                                  2 :\
    \ Bad (DPR modules had errors)\n                              "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: FLG/qualityFlag
  standard_name: qualityFlag
  units: m
qualityPIA:
  _FillValue: 9
  description: "The reliability flag for the effective PIA estimate (pathAtten).\n\
    \                             1 : Reliable\n                             2 : Marginally\
    \ reliable \n                             3 : Unreliable\n                   \
    \          4 : Provides a lower bound to the path-attenuation\n              \
    \               "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SRT/reliabFlag
  standard_name: reliabFlag
  units: dB
seaIceConcentration:
  _FillValue: -9999.9
  description: Sea ice concentration estimated by Ku. Values range from 30 to 100 percent.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: Experimental/seaIceConcentration
  standard_name: seaIceConcentration
  units: '%'
sigmaZeroCorrected:
  _FillValue: -9999.9
  description: Surface backscattering cross section with attenuation correction.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/sigmaZeroCorrected
  standard_name: sigmaZeroCorrected
  units: dB
sigmaZeroMeasured:
  _FillValue: -9999.9
  description: Surface backscattering cross section without attenuation correction.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/sigmaZeroMeasured
  standard_name: sigmaZeroMeasured
  units: dB
sigmaZeroNPCorrected:
  _FillValue: -9999.9
  description: " Surface backscattering cross section with \n                    \
    \      attenuation correction only for non-precipitation particles\n         \
    \                 "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: VER/sigmaZeroNPCorrected
  standard_name: sigmaZeroNPCorrected
  units: dB
snRatioAtRealSurface:
  _FillValue: -9999
  description: Signal/Noise ratio at real surface range bin.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: PRE/snRatioAtRealSurface
  standard_name: snRatioAtRealSurface
  units: ''
typePrecip:
  _FillValue:
  - -1111
  - -9999
  description: Precipitation type. 8 digits to be decoded following GPM ATBD.                         "
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/typePrecip
  standard_name: typePrecip
  units: ''
widthBB:
  _FillValue:
  - -1111.1
  - -9999.9
  description: Width of the bright band.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: CSF/widthBB
  standard_name: widthBB
  units: m
zFactorCorrected:
  _FillValue: -9999.9
  description: Vertical profile of reflectivity with attenuation correction.
  dims:
  - along_track
  - cross_track
  - range
  ndims: 3
  offset_scale: []
  path: SLV/zFactorCorrected
  standard_name: zFactorCorrected
  units: dBZ
zFactorCorrectedESurface:
  _FillValue: -9999.9
  description: Reflectivity factor with attenuation correction at the estimated surface.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/zFactorCorrectedESurface
  standard_name: zFactorCorrectedESurface
  units: dBZ
zFactorCorrectedNearSurface:
  _FillValue: -9999.9
  description: Reflectivity factor with attenuation correction at the near surface.
  dims:
  - along_track
  - cross_track
  ndims: 2
  offset_scale: []
  path: SLV/zFactorCorrectedNearSurface
  standard_name: zFactorCorrectedNearSurface
  units: dBZ
zFactorMeasured:
  _FillValue: -9999.9
  description: Vertical profile of reflectivity without attenuation correction.
  dims:
  - along_track
  - cross_track
  - range
  ndims: 3
  offset_scale: []
  path: PRE/zFactorMeasured
  standard_name: zFactorMeasured
  units: dBZ
