#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 29 13:39:56 2021

@author: ghiggi
"""
'check_Date',
'check_GPM_version',
'check_HHMMSS',
'check_product',
'check_product_type',
'check_time',
'check_GPM_version',
'check_bbox',
'check_product',
'check_scan_mode',
'check_variables',

'create_DPR',
'create_DPR_ENV',
'create_GMI',
'create_GPM_class',
'create_IMERG'
'find_GPM_files',
 
'curl_cmd',
'wget_cmd',
'download_GPM_data',
'download_daily_GPM_data',

'filter_GPM_query',
'filter_daily_GPM_files',
'find_GPM_files',
'find_daily_GPM_PPS_filepaths',
'find_daily_GPM_disk_filepaths',
'get_GPM_PPS_directory',
'get_GPM_disk_directory',
'get_name_first_daily_granule',
'get_time_first_daily_granule',
'granules_Dates',
'granules_end_HHMMSS',
'granules_start_HHMMSS',
'granules_time_info',

'is_empty',
'is_not_empty',
'str_detect',
'str_extract',
'str_pad',
'str_sub',
'str_subset',
'subset_list_by_boolean',


# remove_dict_keys
# initialize_scan_modes
# parse_GPM_ScanTime
# read_GPM
'GPM_Dataset',
'GPM_granule_Dataset',

'GPM_products'
'GPM_variables',
'GPM_variables_dict'
'GPM_1B_NRT_pattern_dict',
'GPM_1B_NRT_products',
'GPM_1B_RS_pattern_dict',
'GPM_1B_RS_products',
'GPM_1C_NRT_products',
'GPM_1C_RS_products',
'GPM_2A_NRT_pattern_dict',
'GPM_2A_NRT_products',
'GPM_2A_RS_pattern_dict',
'GPM_2A_RS_products',
'GPM_DPR_1B_NRT_products',
'GPM_DPR_1B_RS_pattern_dict',
'GPM_DPR_1B_RS_products',
'GPM_DPR_2A_ENV_NRT_products',
'GPM_DPR_2A_ENV_RS_products',
'GPM_DPR_2A_NRT_pattern_dict',
'GPM_DPR_2A_NRT_products',
'GPM_DPR_2A_RS_pattern_dict',
'GPM_DPR_2A_RS_products',
'GPM_DPR_NRT_pattern_dict',
'GPM_DPR_NRT_products',
'GPM_DPR_RS_pattern_dict',
'GPM_DPR_RS_products',
'GPM_IMERG_NRT_pattern_dict',
'GPM_IMERG_NRT_products',
'GPM_IMERG_RS_pattern_dict',
'GPM_IMERG_RS_products',
'GPM_IMERG_pattern_dict',
'GPM_IMERG_products',
'GPM_NRT_products',
'GPM_NRT_products_pattern_dict',
'GPM_PMW_1B_NRT_pattern_dict',
'GPM_PMW_1B_NRT_products',
'GPM_PMW_1B_RS_pattern_dict',
'GPM_PMW_1B_RS_products',
'GPM_PMW_1C_NRT_pattern_dict',
'GPM_PMW_1C_NRT_products',
'GPM_PMW_1C_RS_pattern_dict',
'GPM_PMW_1C_RS_products',
'GPM_PMW_2A_GPROF_NRT_pattern_dict',
'GPM_PMW_2A_GPROF_NRT_products',
'GPM_PMW_2A_GPROF_RS_pattern_dict',
'GPM_PMW_2A_GPROF_RS_products',
'GPM_PMW_2A_PRPS_NRT_pattern_dict',
'GPM_PMW_2A_PRPS_NRT_products',
'GPM_PMW_2A_PRPS_RS_pattern_dict',
'GPM_PMW_2A_PRPS_RS_products',
'GPM_PMW_NRT_pattern_dict',
'GPM_PMW_NRT_products',
'GPM_PMW_RS_pattern_dict',
'GPM_PMW_RS_products',
'GPM_RS_products',
'GPM_RS_products_pattern_dict',
'GPM_products',
'GPM_products_pattern_dict'
