#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 25 11:24:05 2020

@author: ghiggi
"""

# Quality
# incidenceAngle
# sunGlintAngle
# incidenceAngleIndex
# Tc

## AMSU-B  S1
# (89.0 +/- 0.9 GHz, 
# 150.0 +/- 0.9 GHz, 
# 183.31 +/- 1 GHz, 
# 183.31 +/- 3 GHz,
# 183.31 +/- 7 GHz)

# ATMS S1,S2,S3,S4
# 22 channels
# Polarization: QH, QV (quasi horiz/vertical)
# 4 swaths, one for each band K, A(Ka), W, and G

# Saphir S1
# 6 channels
# 183.31 +/- delta GHz where delta = 0.2, 1.1, 2.8, 4.2, 6.8, 11.0

# MHS S1 
# 5 channels (89.0GHzV, 157.0GHzV, 183.31GHz+/-1GHzH, 183.31GHz+/-3GHzH, and 190.31GHzV)

# WindSat S1
# 8 channels ( 10.7V 10.7H 18.7V 18.7H 23.8V 23.8H 37V 37H)

## AMSR2  (S1 S2 S3 S4 S5 S6) 
# Swath 1 has channels 10.65V 10.65H. Swath 2 has channels 18.7V 18.7H. Swath
# 3 has channels 23.8V 23.8H. Swath 4 has channels 36.5V 36.5H. Swath S5 has 2 high
# frequency A-Scan channels (89V 89H). Swath S6 has 2 high frequency B-Scan channels
# (89V 89H).

## AMSRE  (S1 S2 S3 S4 S5 S6) 
# Swath 1 has channels 10.65V 10.65H. Swath 2 has channels 18.7V 18.7H. Swath 3 has
# channels 23.8V 23.8H. Swath 4 has channels 36.5V 36.5H. Swath S5 has 2 high frequency
# A-Scan channels (89V 89H). Swath S6 has 2 high frequency B-Scan channels (89V 89H).

# SSM/I passive (S1, S2)
# microwave instruments flown on the DMSP satellites. Swath S1 has 5 low frequency
# channels (19V 19H 22V 37V 37H). Swath S2 has 2 high frequency channels (85V 85H).

## SSMIS (S1, S2, S3, S4)
# Swath S1 has 3 low frequency
# channels (19V 19H 22V). Swath S2 has 2 low frequency channels (37V 37H). Swath S3
# has 4 high frequency channels (150H 183+/-1H 183+/-3H 183+/-7H). S4 has 2 high
# frequency channels (91V 91H).

## GMI (S1, S2)
## Swath S1 has 9 channels which are similar to TRMM TMI 
# (10V 10H 19V 19H 23V 37V 37H 89V 89H). 
# Swath S2 has 4 channels similar to AMSU-B 
# (166V 166H 183+/-3V 183+/-7V)

## TMI (S1, S2, S3)
# Swath S1 has 2 low resolution channels (10V 10H). 
# Swath S2 has 5 low resolution channels (19V 19H,21V 37V 37H). 
# Swath S3 has 2 high resolution channels (85V 85H)