IRprecipitation:
  _FillValue: -9999.9
  description: Microwave-calibrated IR precipitation estimate.
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: IRprecipitation
  standard_name: IRprecipitation
  units: mm/hr
PMWobservationTime:
  _FillValue: -9999
  description: "Observation time (from the beginnning of the current half hour) \
    \ of the instantaneous PMW-only precipitation estimate covering the current 30-minute period\n\
    \ Values range from 0 to 29 minutes."                            
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: HQobservationTime
  standard_name: HQobservationTime
  units: minutes
PMWprecipSource:
  _FillValue: -9999.9
  description: "Sensor used for HQprecipitation:\n\
    \ 0 = no observation\n\                           
    \ 1 = TMI\n\
    \ 2 = TCI\n\
    \ 3 = AMSR\n\    
    \ 4 = SSMI\n\
    \ 5 = SSMIS\n\                                                    
    \ 6 = AMSU\n\  
    \ 7 = MHS\n\     
    \ 8 = Megha-Tropiques\n\                                           
    \ 9 = GMI\n\                           
    \ 10 = GCI\n\
    \ 11 = ATMS\n\                        
    \ 12 = AIRS\n\
    \ 13 = TOVS\n\                            
    \ 14 = CrlS"
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: HQprecipSource
  standard_name: HQprecipSource
  units: mm/hr
PMWprecipitation:
  _FillValue: -9999.9
  description: Instananeous microwave-only precipitation estimate.
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: HQprecipitation
  standard_name: HQprecipitation
  units: mm/hr
precipitationCal:
  _FillValue: -9999.9
  description: Precipitation estimate using gauge calibration over land.
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: precipitationCal
  standard_name: precipitationCal
  units: mm/hr
precipitationQualityIndex:
  _FillValue: -9999
  description: Estimated quality of precipitationCal where 0 is worse and 100 is better. 
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: precipitationQualityIndex
  standard_name: precipitationQualityIndex
  units: ''
precipitationUncal:
  _FillValue: -9999.9
  description: Precipitation estimate with no gauge calibration.
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: precipitationUncal
  standard_name: precipitationUncal
  units: mm/hr
probabilityLiquidPrecipitation:
  _FillValue: -9999
  description: " Probability of liquid precipitation\n\
    \ 0 = definitely frozen.\n\
    \ 100 = definitely liquid.\n\                                        
    \ 50 = equal probability frozen or liquid."                                       
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: probabilityLiquidPrecipitation
  standard_name: probabilityLiquidPrecipitation
  units: ''
randomError:
  _FillValue: -9999.9
  description: Random error estimate of precipitation.
  dims:
  - time
  - lon
  - lat
  ndims: 3
  offset_scale: []
  path: randomError
  standard_name: randomError
  units: mm/hr
