# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev101+g71f6585.d20230313'
__version_tuple__ = version_tuple = (0, 1, 'dev101', 'g71f6585.d20230313')
