#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 17 13:49:03 2020

@author: ghiggi
"""

/1C/AMSR2/
/1C/ATMS/
/1C/GMI/
/1C/MHS/
/1C/SAPHIR/
/1C/SSMIS/
/1C/TMI/

GMI1B/

/GPROF/AMSR2/
/GPROF/ATMS/
/GPROF/GMI/
/GPROF/MHS/
/GPROF/SAPHIR/
/GPROF/SSMIS/
/GPROF/TMI/

PRPS/

/radar/DprL2/
/radar/KaL2/
/radar/KuL2/