---
name: Lint
on: [push, pull_request, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Ruff
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ruff --all-files
      - name: Black
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: black --all-files
      - name: blackdoc
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: blackdoc --all-files
      - name: codespell
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: codespell --all-files
